# NumPy Basics

In [1]:
import numpy as np
import pandas as pd


# Exercise 1: Create a NumPy array of 10 zeros and then update the fifth value to 11.


In [4]:
df = np.zeros(10)
df[4]=11
df

array([ 0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.])

# Exercise 2: Array Operations:Given two arrays `A = np.array([1, 2, 3])` and `B = np.array([4, 5, 6])`, calculate the element-wise sum.


In [5]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

sum_array = A + B
sum_array

array([5, 7, 9])

# Exercise 3: NumPy Slicing: Create a 1D NumPy array with values from 1 to 10, then use slicing to obtain the middle four elements.


In [8]:
df1 = np.random.randint(1,10,10)
print(df1)
print(df1[3:7])

[8 6 3 2 9 9 1 7 1 5]
[2 9 9 1]


# Exercise 4: Pandas Series Creation: Create a Pandas Series from a list of your choice and display its basic statistics using `.describe()`.


In [10]:
df2 = pd.DataFrame(df1)
df2.describe()

0
count  10.00000
mean    5.10000
std     3.17805
min     1.00000
25%     2.25000
50%     5.50000
75%     7.75000
max     9.00000

# Exercise 5: Data Frame Basics: Create a DataFrame with three columns: 'Name', 'Age', and 'City'. Populate it with data of your choice and display the first two rows


In [13]:
data = { 'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 'Age': [25, np.nan, 30, np.nan, 22], 'Salary': [50000, 60000, np.nan, 55000, np.nan] }
df4 = pd.DataFrame(data)
df4[:2] 

Name   Age   Salary
0  Alice  25.0  50000.0
1    Bob   NaN  60000.0

# Exercise 6: Column Selection: Given a DataFrame, select and print only the 'Age' column.


In [14]:
df4['Age']

0    25.0
1     NaN
2    30.0
3     NaN
4    22.0
Name: Age, dtype: float64

# Exercise 7: Row Filtering: From a DataFrame, filter and display rows where 'Age' is greater than 25.


In [19]:
df4[df4.Age>25]

Name   Age  Salary
2  Charlie  30.0     NaN


# Exercise 8: DataFrame Operations: Add a new column 'Age Next Year' to a DataFrame that adds 1 to the current 'Age' column.


In [20]:
df4["Age Next Year"] = df4.Age + 1
df4

Name   Age   Salary  Age Next Year
0    Alice  25.0  50000.0           26.0
1      Bob   NaN  60000.0            NaN
2  Charlie  30.0      NaN           31.0
3    David   NaN  55000.0            NaN
4      Eve  22.0      NaN           23.0

# Exercise 9: Handling Missing Values: Given a DataFrame with missing values, use `.fillna()` to `Inline code`replace them with the mean of their column.


In [24]:
df4.Age = df4.Age.fillna(df4.Age.mean())
df4.Salary = df4.Salary.fillna(df4.Salary.mean())
df4['Age Next Year'] = df4['Age Next Year'].fillna(df4['Age Next Year'].mean())
df4

Name        Age   Salary  Age Next Year
0    Alice  25.000000  50000.0      26.000000
1      Bob  25.666667  60000.0      26.666667
2  Charlie  30.000000  55000.0      31.000000
3    David  25.666667  55000.0      26.666667
4      Eve  22.000000  55000.0      23.000000

# Exercise 10: Merging DataFrames: Merge two DataFrames on a common column named 'ID' using an inner join.
1 = ({'ID': [1, 2, 3], 'Value': ['A', 'B', 'C']})

2 = ({'ID': [1, 2, 4], 'Description': ['X', 'Y', 'Z']})

In [30]:
U1 = pd.DataFrame({'ID': [1, 2, 3], 'Value': ['A', 'B', 'C']})
U2 = pd.DataFrame({'ID': [1, 2, 4], 'Description': ['X', 'Y', 'Z']})

merged_df = pd.merge(U1,U2,how='inner',on='ID')

merged_df

ID Value Description
0   1     A           X
1   2     B           Y